"""add user confirmed field

Revision ID: 157a14257e82
Revises: 3f62a6732e18
Create Date: 2021-03-11 10:26:50.287515

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "157a14257e82"
down_revision = "3f62a6732e18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("confirmed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "confirmed")
    # ### end Alembic commands ###
