"""empty message

Revision ID: 7fd01c7f7556
Revises: c9dcaa62cc91
Create Date: 2021-03-07 15:05:22.795150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd01c7f7556'
down_revision = 'c9dcaa62cc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    # ### end Alembic commands ###
